<a href="https://colab.research.google.com/github/pb111/Deep-Learning-with-PyTorch/blob/master/Tensor_operations_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a class="anchor" id="0"></a>
# **Tensor Operations in PyTorch**


In this notebook, I will discuss Tensor Operations in PyTorch. Tensors are the basic building blocks of PyTorch library. The data structure used in PyTorch is graph based and tensor based. Therefore, it is important to understand basic operations and defining tensors.

<a class="anchor" id="0.1"></a>
# **Table of Contents**


1.	[Introduction to Tensors](#1)
2.	[Check for Tensor Object](#2)
3.	[Create Tensors](#3)
4.	[Diagonal Matrix of Tensors](#4)
5.	[Shape of the Tensor](#5)
6.	[Access elements in Tensor](#6)
7.	[Specify data types of elements](#7)
8.	[Tensor to/from NumPy Array](#8)
9.	[Random Sampling of Tensors](#9)
10.	[Basic Statistics with Tensors](#10)
11.	[Arithmetic Operations on Tensors](#11)
12.	[CPU v/s  GPU Tensor](#12)



# **1. Introduction to Tensors** <a class="anchor" id="1"></a>

[Table of Contents](#0.1)


- PyTorch uses [Tensor](https://machinelearningmastery.com/introduction-to-tensors-for-machine-learning/) as its core data structure, which is similar to Numpy array. 

- With appropriate software and hardware available, tensors provide acceleration of various mathematical operations. These operations when carried out in a large number in Deep Learning make a huge difference in speed.

- **Tensors** are the core data structure used in PyTorch.

- Tensor is a fancy name given to matrices. Familiarity with NumPy arrays will help us to understand PyTorch Tensors. 

- A scalar value is represented by a 0-dimensional Tensor. Similarly a column/row matrix use a 1-D Tensor and so on. 

- Some examples of Tensors with different dimensions are shown below to give us a better picture.

![PyTorch Tensors](https://www.learnopencv.com/wp-content/uploads/2019/05/PyTorch-Tensors.jpg)

# **2. Check for Tensor Object** <a class="anchor" id="2"></a>

[Table of Contents](#0.1)


- In this section, we will check whether the created object is a tensor object.

- First, we will create a list x and check whether it ia a tensor.

- The `is_tensor` function helps to check whether the created object is tensor.

In [1]:
import torch


# define a list x
x = [10, 20, 30, 40, 50]


# check whether x is tensor object
torch.is_tensor(x)


False

- The above command shows that x is not tensor.

- The `is_storage` function checks whether the object is stored as tensor object.

In [2]:
# check whether x is stored as tensor object
torch.is_storage(x)

False

- The above command shows that x is not stored as tensor object.

- Now, we will create an object that contains random numbers from Torch, similar to NumPy library. 

- We can check the object type and storage type as follows -

In [0]:
# first, we will create a tensor y
y = torch.randn(1,2,3,4,5)

In [4]:
# now check whether y is tensor object
torch.is_tensor(y)

True

- The above command shows that y is a tensor object.



- Now, let's check whether y is stored as tensor object.

In [5]:
torch.is_storage(y)

False

- We can see that y is not stored as tensor object.

- The y object is a tensor. But, it is not stored. 
- To check the total number of elements in the input tensor object, the numerical element function can be used.
- Now, we will check the total number of elements in the input tensor as follows -

In [6]:
# check the total number of elements in y
torch.numel(y)

120

- We can see that the total number of elements in y is 120.

# **3. Create Tensors** <a class="anchor" id="3"></a>

[Table of Contents](#0.1)

- Now, we will create a PyTorch Tensor. 

In [7]:
# Create a Tensor with just ones in a column
a = torch.ones(5)


# Print the tensor we created
print(a)

tensor([1., 1., 1., 1., 1.])


In [8]:
# Create a Tensor with just zeros in a column
b = torch.zeros(5)


# Print the tensor we created
print(b)

tensor([0., 0., 0., 0., 0.])


- We can similarly create Tensor with custom values as shown below.

In [9]:
# Create a Tensor with custom values
c = torch.tensor([1.0, 2.0, 3.0, 4.0, 5.0])

# Print the tensor we created
print(c)

tensor([1., 2., 3., 4., 5.])


- In all the above cases, we have created vectors or Tensors of dimension 1. Now, we will create some tensors of higher dimensions.

- First, we will create a tensor of zeros with higher dimensions. 

In [10]:
# Create a Tensor with zeros with higher dimensions
d = torch.zeros(4,4)

# Print the tensor we created
print(d)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [11]:
# now we will count the numerical elements in d
torch.numel(d)

16

- So, the tensor `d` have 16 elements in it.

In [12]:
# Create a Tensor with zeros with higher dimensions
e = torch.zeros(3,2)

# Print the tensor we created
print(e)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [13]:
# Create a Tensor with ones with higher dimensions
f = torch.ones(3,2)

# Print the tensor we created
print(f)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [14]:
# Create a Tensor with customized values with higher dimensions
g = torch.tensor([[1.0, 2.0], [3.0, 4.0]])

# Print the tensor we created
print(g)

tensor([[1., 2.],
        [3., 4.]])


In [15]:
# Create a 3D Tensor
h = torch.tensor([[[1.0, 2.0], [3.0, 4.0]], [[5.0, 6.0], [7.0, 8.0]]])

# Print the 3d tensor we created
print(h)

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


# **4. Diagonal Matrix of Tensors** <a class="anchor" id="4"></a>

[Table of Contents](#0.1)

- Like NumPy operations, the eye function creates a diagonal matrix of tensors.
- The diagonal elements have ones, and off diagonal elements have zeros. 

In [16]:
# create a diagonal matrix of tensors with dimensions (3,3)
i = torch.eye(3,3)

print(i)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [17]:
# create a diagonal matrix of tensors with dimensions (5,5)
j = torch.eye(5,5)

print(j)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


# **5. Shape of the Tensor** <a class="anchor" id="5"></a>

[Table of Contents](#0.1)

- We can also find out the shape of a Tensor using **shape** method as follows -

In [18]:
# Create a Tensor with customized values with higher dimensions
k = torch.tensor([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])

print(k)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


In [19]:
# Print the shape of k
print(k.shape)

torch.Size([3, 2])


- We can see that k has dimensions (3,2).

In [20]:
# Create a Tensor with ones with higher dimensions
l = torch.ones(3,2)

# Print the shape of f
print(l.shape)

torch.Size([3, 2])


In [21]:
# Create a 3D Tensor
m = torch.tensor([[[1.0, 2.0], [3.0, 4.0]], [[5.0, 6.0], [7.0, 8.0]]])

# Print the shape of m
print(m.shape)


torch.Size([2, 2, 2])


# **6. Access elements in Tensor** <a class="anchor" id="6"></a>

[Table of Contents](#0.1)

### **Access elements of 1D Tensor**

- Now we know how to create tensors, 

- Let’s see how we can access an element in a Tensor. 

- First let’s see how to do this for 1D Tensor or a vector.

In [22]:
# Create a Tensor with custom values
n = torch.tensor([1.0, 2.0, 3.0, 4.0, 5.0])

# Get element at index 2
print(n[2])

tensor(3.)


### **Access elements of 2D Tensor**

- To access one particular element in a tensor, we will need to specify indices equal to the dimension of the tensor. 
- So for tensor n we only had to specify one index as in the above case.
- But, for tensor o we need to specify two indices as in the below case. 

In [23]:
# All indices starting from 0

# Create a Tensor with customized values with higher dimensions
o = torch.tensor([[1.0, 2.0], [3.0, 4.0]])

# Get element at row 1, column 0
print(o[1,0])

tensor(3.)


- We can define the two indices separately as follows-

In [24]:
# We can also use the following
print(o[1][0])

tensor(3.)


### **Access elements of 3D Tensor**

- We can access elements of 3D Tensor as follows:-

In [25]:
# Create a 3D Tensor
p = torch.tensor([[[1.0, 2.0], [3.0, 4.0]], [[5.0, 6.0], [7.0, 8.0]]])

# Access elements at (1,0,0) position
print(p[1,0,0])

tensor(5.)


In [26]:
# We can access the same element at (1,0,0) position as follows -
print(p[1][0][0])

tensor(5.)


### **Access one entire row in a 2D Tensor**

In [27]:
# Create a Tensor q
q = torch.tensor([[1.0, 2.0], [3.0, 4.0]])

# print all elements of q
print(q[:])

tensor([[1., 2.],
        [3., 4.]])


In [28]:
# access first row of q
print(q[0,:])

tensor([1., 2.])


In [29]:
# access second column of q
print(q[:,1])

tensor([2., 4.])


In [30]:
# create a Tensor r
r = torch.tensor([1.0, 2.0, 3.0, 4.0, 5.0])

# all elements from index 1 to 2 (inclusive)
print(r[1:3])

tensor([2., 3.])


In [31]:
# all elements till index 4 (exclusive)
print(r[:4])

tensor([1., 2., 3., 4.])


# **7. Specify data types of elements** <a class="anchor" id="7"></a>

[Table of Contents](#0.1)


- Whenever we create a tensor, PyTorch decides the data type of the elements of the tensor such that the data type can cover all the elements of the tensor. 

- We can override this by specifying the data type while creating the tensor.

In [32]:
int_tensor = torch.tensor([[1,2,3],[4,5,6]])
print(int_tensor.dtype)

torch.int64


In [33]:
# data type if we change any one element to floating point number
int_tensor = torch.tensor([[1,2,3],[4.,5,6]])
print(int_tensor.dtype)

torch.float32


In [34]:
print(int_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [35]:
# This can be overridden as follows
int_tensor = torch.tensor([[1,2,3],[4.,5,6]], dtype=torch.int32)
print(int_tensor.dtype)

torch.int32


In [36]:
print(int_tensor)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


# **8. Tensor to/from NumPy Array** <a class="anchor" id="8"></a>

[Table of Contents](#0.1)


- PyTorch Tensors and NumPy arrays are very similar. 
- So, it is possible to convert one data structure into another. 
- We can do it as follows -

In [37]:
# import NumPy
import numpy as np

# create a tensor s
s = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
 
# convert tensor to numpy array
s_numpy = s.numpy()
print(s_numpy)

[[1. 2.]
 [3. 4.]]


In [38]:
# convert numpy array to tensor
t = np.array([[8,7,6,5],[4,3,2,1]])
t_tensor = torch.from_numpy(t)
print(t_tensor)
 

tensor([[8, 7, 6, 5],
        [4, 3, 2, 1]])


# **9. Random Sampling of Tensors** <a class="anchor" id="9"></a>

[Table of Contents](#0.1)


- The deep learning task requires reproducing the same set of results to maintain consistency. 
- In such a case, manual seed needs to be set as follows -


In [39]:
import torch

torch.manual_seed(1234)

In [40]:
torch.manual_seed(1234)

u = torch.randn(4,4)

u

tensor([[-0.1117, -0.4966,  0.1631, -0.8817],
        [ 0.0539,  0.6684, -0.0597, -0.4675],
        [-0.2153,  0.8840, -0.7584, -0.3689],
        [-0.3424, -1.4020,  0.3206, -1.0219]])

- Now, everytime `u` produce the same result.

In [41]:
u

tensor([[-0.1117, -0.4966,  0.1631, -0.8817],
        [ 0.0539,  0.6684, -0.0597, -0.4675],
        [-0.2153,  0.8840, -0.7584, -0.3689],
        [-0.3424, -1.4020,  0.3206, -1.0219]])

- The seed value can be customized. 
- The random number is generated purely by chance. 
- Random numbers can also be generated from a statistical distribution.

### **Random Sampling from Uniform Distribution**

- In a continuous uniform distribution, each number has an equal chance of being selected. 
- Random sampling from a uniform distribution can be done as follows.
- In the following example, the start is 0 and the end is 1 and between those two digits, all 16 elements are selected.

In [42]:
# random sampling from uniform distribution
torch.Tensor(4,4).uniform_(0,1)

tensor([[0.2837, 0.6567, 0.2388, 0.7313],
        [0.6012, 0.3043, 0.2548, 0.6294],
        [0.9665, 0.7399, 0.4517, 0.4757],
        [0.7842, 0.1525, 0.6662, 0.3343]])

### **Random Sampling from Bernoulli Distribution**

- In statistics, the Bernoulli distribution is considered as the discrete probability distribution, which has two possible outcomes. 
- If the event happens, then the value is 1, and if the event does not happen, then the value is 0.
- From the Bernoulli distribution, we create sample tensors by considering the uniform distribution of size 4 and 4 in a matrix format.
- Random Sampling from Bernoulli distribution can be done as follows.

In [43]:
# random sampling from bernoulli distribution
torch.bernoulli(torch.Tensor(4,4).uniform_(0,1))

tensor([[0., 0., 0., 0.],
        [1., 0., 1., 0.],
        [1., 0., 1., 1.],
        [0., 0., 0., 0.]])

### **Random Sampling from Multinomial Distribution**

- In a multinomial distribution, we can choose with a replacement or without a replacement.
- By default, the multinomial function picks up without a replacement and returns the result as an index position for the tensors.

In [44]:
torch.Tensor([10,20,30,40,50,60,70,80,90,100,110,120])

tensor([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100., 110., 120.])

In [45]:
torch.multinomial(torch.Tensor([10,20,30,40,
                                50,60,70,80,
                                90,100,110,120]),
                 3)

tensor([10,  7,  5])

- Sampling from multinomial distribution with a replacement returns the tensors’ index values.
- If we need to run it with a replacement, then we need to specify that while sampling.

In [46]:
torch.multinomial(torch.Tensor([10,20,30,40,
                                50,60,70,80,
                                90,100,110,120]),
                  5, replacement=True)

tensor([11,  3,  4,  8,  6])

### **Random Sampling from Normal Distribution**


- The process of creating a set of random numbers generated from a normal distribution is as follows.



In [47]:
torch.normal(mean = torch.arange(1., 11.),
             std = torch.arange(1, 0, -0.1))

tensor([-0.0413,  2.0632,  3.4637,  3.9581,  5.1089,  5.6602,  6.8973,  7.4543,
         9.0422, 10.0337])

In [48]:
torch.normal(mean = 0.5,
             std = torch.arange(1., 6.))

tensor([ 1.1638,  2.5794,  6.0301,  3.1352, -0.6746])

In [49]:
torch.normal(mean = 0.5,
             std = torch.arange(0.2,0.6))

tensor([0.4939])

# **10. Basic Statistics with Tensors** <a class="anchor" id="10"></a>

[Table of Contents](#0.1)


- We can compute basic statistics, such as mean, median, mode, and so forth, from a Torch tensor.

- Computation of basic statistics using PyTorch enables the user to apply probability distributions and statistical tests to make inferences from data.

### **Mean Computation**

- The mean computation is simple to write for a 1D tensor.
- However, for a 2D tensor, an extra argument needs to be passed as a mean, median, or mode computation, across which the dimension needs to be specified.

In [50]:
# computing the mean
torch.mean(torch.tensor([10., 20., 30., 40., 50.]))

tensor(30.)

In [51]:
# declare a tensor
v = torch.randn(4,5)
v

tensor([[ 0.9570, -0.5510,  2.6617,  2.1479,  1.2907],
        [ 0.2612, -0.5862, -1.5105, -0.1225,  0.8078],
        [-1.1421,  2.0506,  0.5289, -0.5447,  0.8097],
        [ 1.1226, -1.6121,  0.4752,  0.5868, -0.2878]])

In [52]:
# calculate mean across columns
torch.mean(v,dim=0)

tensor([ 0.2997, -0.1746,  0.5388,  0.5169,  0.6551])

In [53]:
# calculate mean across rows
torch.mean(v,dim=1)

tensor([ 1.3013, -0.2300,  0.3405,  0.0569])

- Median, mode and standard deviation computation can be written in the same way.

In [54]:
# calculate median across columns
torch.median(v,dim=0)

torch.return_types.median(values=tensor([ 0.2612, -0.5862,  0.4752, -0.1225,  0.8078]), indices=tensor([1, 1, 3, 1, 1]))

In [55]:
# calculate median across rows
torch.median(v,dim=1)

torch.return_types.median(values=tensor([ 1.2907, -0.1225,  0.5289,  0.4752]), indices=tensor([4, 3, 2, 2]))

In [56]:
# compute mode
torch.mode(v)

torch.return_types.mode(values=tensor([-0.5510, -1.5105, -1.1421, -1.6121]), indices=tensor([1, 2, 0, 1]))

In [57]:
# compute mode across rows
torch.mode(v,dim=0)

torch.return_types.mode(values=tensor([-1.1421, -1.6121, -1.5105, -0.5447, -0.2878]), indices=tensor([2, 3, 1, 2, 3]))

In [58]:
# compute mode across columns
torch.mode(v,dim=1)

torch.return_types.mode(values=tensor([-0.5510, -1.5105, -1.1421, -1.6121]), indices=tensor([1, 2, 0, 1]))

### **Compute Standard Deviation**

- Standard deviation shows the deviation from the measures of central tendency.
- It indicates the consistency of the data/variable. 
- It shows whether there is enough fluctuation in data or not.

In [59]:
# compute standard deviation
torch.std(v)

tensor(1.1810)

In [60]:
# compute standard deviation across columns
torch.std(v,dim=0)

tensor([1.0311, 1.5630, 1.7040, 1.1833, 0.6684])

In [61]:
# compute standard deviation across rows
torch.std(v,dim=1)

tensor([1.2366, 0.8799, 1.2412, 1.0601])

### **Compute Variance**

In [62]:
# compute variance
torch.var(v)

tensor(1.3948)

In [63]:
# compute variance across columns
torch.var(v, dim=0)

tensor([1.0632, 2.4430, 2.9035, 1.4003, 0.4467])

In [64]:
# compute variance across rows
torch.var(v, dim=1)

tensor([1.5293, 0.7741, 1.5405, 1.1239])

# **11. Arithmetic Operations on Tensors** <a class="anchor" id="11"></a>


[Table of Contents](#0.1)

- Now, we will see how to perform arithmetic operations on PyTorch tensors.


In [0]:
# Create two tensors
tensor1 = torch.tensor([[1,2,3],[4,5,6]])
tensor2 = torch.tensor([[-1,2,-3],[4,-5,6]])

In [66]:
# Addition
print(tensor1+tensor2)

tensor([[ 0,  4,  0],
        [ 8,  0, 12]])


In [67]:
# We can also use
print(torch.add(tensor1,tensor2))

tensor([[ 0,  4,  0],
        [ 8,  0, 12]])


In [68]:
# Subtraction
print(tensor1-tensor2)

tensor([[ 2,  0,  6],
        [ 0, 10,  0]])


In [69]:
# We can also use
print(torch.sub(tensor1,tensor2))

tensor([[ 2,  0,  6],
        [ 0, 10,  0]])


In [70]:
# Multiplication
# Tensor with Scalar
print(tensor1 * 2)

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])


In [71]:
# Tensor with another tensor
# Elementwise Multiplication
print(tensor1 * tensor2)

tensor([[ -1,   4,  -9],
        [ 16, -25,  36]])


In [72]:
# Matrix multiplication
tensor3 = torch.tensor([[1,2],[3,4],[5,6]])
print(torch.mm(tensor1,tensor3))

tensor([[22, 28],
        [49, 64]])


In [73]:
# Division
# Tensor with scalar
print(tensor1/2)

tensor([[0, 1, 1],
        [2, 2, 3]])


In [74]:
# Tensor with another tensor
# Elementwise division
print(tensor1/tensor2)

tensor([[-1,  1, -1],
        [ 1, -1,  1]])


# **12. CPU v/s GPU Tensor** <a class="anchor" id="12"></a>

[Table of Contents](#0.1)


- PyTorch has different implementation of Tensor for CPU and GPU. 
- Every tensor can be converted to GPU in order to perform massively parallel, fast computations. 
- All operations that will be performed on the tensor will be carried out using GPU-specific routines that come with PyTorch.
- We will first see how to create a tensor for GPU.

In [0]:
# Create a tensor for CPU
# This will occupy CPU RAM
tensor_cpu = torch.tensor([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]], device='cpu')

In [0]:
# Create a tensor for GPU
# This will occupy GPU RAM
tensor_gpu = torch.tensor([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]], device='cuda')

- Just like tensor creation, the operations performed for CPU and GPU tensors are also different and consume RAM corresponding to the device specified.

In [0]:
# This uses CPU RAM
tensor_cpu = tensor_cpu * 5 

In [0]:
# This uses GPU RAM
# Focus on GPU RAM Consumption
tensor_gpu = tensor_gpu * 5

- The key point to note here is that no information flows to CPU in the GPU tensor operations (except if we print or access the tensor).

- We can move the GPU tensor to CPU and vice versa as shown below.

In [0]:
# Move GPU tensor to CPU
tensor_gpu_cpu = tensor_gpu.to(device='cpu')

In [0]:
# Move CPU tensor to GPU
tensor_cpu_gpu = tensor_cpu.to(device='cuda')

[Go to Top](#0)